### ISSUE TITLE
Баг при вызове integration_module_edit()

### ISSUE THREAD

**Issue by stratila** [retailcrm/api-client-python#23]
файл v5.py строка 391
```python
return self.post('/integration-modules/' + str(configuration['code'])) + '/edit'
```
```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/bogdanstratila/Desktop/PostFiles/limo-app/venv/lib/python3.8/site-packages/retailcrm/versions/v5.py", line 391, in integration_module_edit
    return self.post('/integration-modules/' + str(configuration['code'])) + '/edit'
TypeError: unsupported operand type(s) for +: 'Response' and 'str'
```

**Comment by gwinn** [comment]
Входные данные можете указать?

**Comment by gwinn** [comment]
Проверили на 3.7-3.9 проблем не обнаружили, без входных данных тяжело судить, что пошло не так
